"""Toy-task (xor/spiral/circles) wiring through CoreTrainer.

These selectable demo tasks previously raised "Unknown dataset" in the demo.
They are now generated by ``bioplausible.data.vision`` and train through the
standard ``CoreTrainer`` path (2 features, 2 classes).
"""

import pytest
import torch

from bioplausible.core.trainer import CoreTrainer, TrainerConfig
from bioplausible.data.vision import create_data_loaders


@pytest.mark.parametrize("task", ["xor", "spiral", "circles"])
def test_toy_loader_shapes(task):
    train_loader, _ = create_data_loaders(task, batch_size=32)
    x, y = next(iter(train_loader))
    assert x.shape[1:] == (2,)
    assert x.dtype == torch.float32
    assert set(y.unique().tolist()).issubset({0.0, 1.0})
    # Toy classification labels are Long class indices (one_hot/scatter host).
    assert y.dtype == torch.long


@pytest.mark.parametrize(
    "task,features",
    [("iris", 4), ("wine", 13), ("breast_cancer", 30)],
)
def test_tabular_loader_shapes(task, features):
    train_loader, _ = create_data_loaders(task, batch_size=16)
    x, y = next(iter(train_loader))
    assert x.shape[1:] == (features,)
    assert x.dtype == torch.float32
    assert y.dtype == torch.long


@pytest.mark.parametrize("task", ["xor", "spiral", "circles"])
def test_toy_task_trains_through_core_trainer(task):
    config = TrainerConfig(
        model="backprop_mlp",
        task=task,
        epochs=1,
        model_kwargs={"input_dim": 2, "hidden_dim": 16, "output_dim": 2},
    )
    history = CoreTrainer(config).fit()
    assert len(history) == 1
    assert 0.0 <= history[-1].val_accuracy <= 1.0
