"""
Analysis Package
"""

from .dynamics import DynamicsAnalyzer
from .energy_landscape import (
    EnergyLandscape,
    compute_energy_landscape,
    plot_energy_landscape,
)
from .failure_manifesto import FailureManifestoGenerator
from .pareto import (
    ParetoFrontier,
    ParetoPoint,
    compute_pareto_frontier,
    knee_detection,
    pareto_frontier_from_trials,
    plot_pareto_3d,
    plot_pareto_frontier,
)
from .results import compute_statistics, get_rankings, load_trials
from .scaling import (
    ChinchillaLaw,
    PowerLawFit,
    ScalingLawFitter,
    compute_scaling_exponent,
    extrapolate_performance,
    fit_chinchilla_law,
    fit_power_law,
)
from .tile_dynamics import (
    DynamicTileAlgorithm,
    DynamicTileConfig,
    TileGrowthConfig,
    TileGrowthManager,
    TileMerger,
    TileMetrics,
    TileSplitter,
    create_dynamic_model,
)
from .tile_profiler import (
    BenchmarkConfig,
    BenchmarkResult,
    BenchmarkRunner,
    LearningMonitor,
    MemoryProfiler,
    ProfileResult,
    TileAlgorithmProfiler,
    TileStats,
    create_profiler,
    run_benchmark,
)
from .tile_research import (
    AblationConfig,
    AblationStudy,
    ExperimentConfig,
    ExperimentTracker,
    MetricCollector,
    MetricEntry,
    VisualizationHelper,
    create_ablation_study,
    create_metric_collector,
    create_tracker,
    create_visualization_helper,
)

__all__ = [
    "AblationConfig",
    "AblationStudy",
    "BenchmarkConfig",
    "BenchmarkResult",
    "BenchmarkRunner",
    "ChinchillaLaw",
    "DynamicTileAlgorithm",
    "DynamicTileConfig",
    "DynamicsAnalyzer",
    "EnergyLandscape",
    "ExperimentConfig",
    "ExperimentTracker",
    "FailureManifestoGenerator",
    "LearningMonitor",
    "MemoryProfiler",
    "MetricCollector",
    "MetricEntry",
    "ParetoFrontier",
    "ParetoPoint",
    "PowerLawFit",
    "ProfileResult",
    "ScalingLawFitter",
    "TileAlgorithmProfiler",
    "TileGrowthConfig",
    "TileGrowthManager",
    "TileMerger",
    "TileMetrics",
    "TileSplitter",
    "TileStats",
    "VisualizationHelper",
    "compute_energy_landscape",
    "compute_pareto_frontier",
    "compute_scaling_exponent",
    "compute_statistics",
    "create_ablation_study",
    "create_dynamic_model",
    "create_metric_collector",
    "create_profiler",
    "create_tracker",
    "create_visualization_helper",
    "extrapolate_performance",
    "fit_chinchilla_law",
    "fit_power_law",
    "get_rankings",
    "knee_detection",
    "load_trials",
    "pareto_frontier_from_trials",
    "plot_energy_landscape",
    "plot_pareto_3d",
    "plot_pareto_frontier",
    "run_benchmark",
]
