"""Substrate-native deployment model classes (vision, graph, RL, timeseries).

These models extend :class:`~bioplausible.core.local_learning.TileAlgorithm`
with domain-specific feature extractors and a ``build_tile_head`` head, then
register under the ``tile`` family (``conv_tile``, ``graph_tile``,
``rl_tile``, ``timeseries_tile``).
"""

from bioplausible.zoo.models.deployments.base import (
    ConvDeploymentConfig,
    DeploymentConfig,
    GraphDeploymentConfig,
    RLDeploymentConfig,
    TemporalDeploymentConfig,
    build_tile_head,
    create_deployment_model,
)
from bioplausible.zoo.models.deployments.graph import (
    GraphAttentionLayer,
    GraphEquiTileLayer,
    GraphTileNet,
    GraphTileNetConfig,
    add_self_loops,
    aggregate_messages,
    create_graph_model,
    create_molecule_model,
    create_social_graph_model,
    scatter_max,
    scatter_mean,
    scatter_sum,
)
from bioplausible.zoo.models.deployments.rl import (
    RecurrentRLTileNet,
    RLTIleNet,
    RLTIleNetConfig,
    RolloutBuffer,
    compute_gae,
    create_atari_model,
    create_mujoco_model,
    create_recurrent_rl_model,
    create_rl_model,
)
from bioplausible.zoo.models.deployments.timeseries import (
    TemporalAttentionLayer,
    TemporalPositionalEncoding,
    TimeSeriesConfig,
    TimeSeriesEquiTileLayer,
    TimeSeriesTileNet,
    create_anomaly_detection_model,
    create_classification_model,
    create_forecasting_model,
)
from bioplausible.zoo.models.deployments.vision import (
    ConvFeatureExtractor,
    ConvTileNet,
    ConvTileNetConfig,
    VisionAugmentation,
    create_cifar_model,
    create_imagenet_model,
    create_mnist_model,
    create_vision_model,
)

__all__ = [
    "ConvDeploymentConfig",
    "ConvFeatureExtractor",
    "ConvTileNet",
    "ConvTileNetConfig",
    "DeploymentConfig",
    "GraphAttentionLayer",
    "GraphDeploymentConfig",
    "GraphEquiTileLayer",
    "GraphTileNet",
    "GraphTileNetConfig",
    "RLDeploymentConfig",
    "RLTIleNet",
    "RLTIleNetConfig",
    "RecurrentRLTileNet",
    "RolloutBuffer",
    "TemporalAttentionLayer",
    "TemporalDeploymentConfig",
    "TemporalPositionalEncoding",
    "TimeSeriesConfig",
    "TimeSeriesEquiTileLayer",
    "TimeSeriesTileNet",
    "VisionAugmentation",
    "add_self_loops",
    "aggregate_messages",
    "build_tile_head",
    "compute_gae",
    "create_anomaly_detection_model",
    "create_atari_model",
    "create_cifar_model",
    "create_classification_model",
    "create_deployment_model",
    "create_forecasting_model",
    "create_graph_model",
    "create_imagenet_model",
    "create_mnist_model",
    "create_molecule_model",
    "create_mujoco_model",
    "create_recurrent_rl_model",
    "create_rl_model",
    "create_social_graph_model",
    "create_vision_model",
    "scatter_max",
    "scatter_mean",
    "scatter_sum",
]
